version: '3.7'
services:
  nginx-proxy:
    build: ./nginx
    image: jhenck57/pavementhub-nginx
    container_name: proxy
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/error.log:/etc/nginx/error_log.log
      #- ./nginx/cache/:/etc/nginx/cache
      #- /datastore/certifications/nginx/nginx-simple-docker/certs/:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENV=development
      - APPLICATION_URL=http://pavement-hub.pavement.rutgers.edu

    ports:
      - 80:80
      - 443:443
    networks:
      - front-proxy

  jupyter-minimal:
    image: jupyter/minimal-notebook
    container_name: jupyter.minimal
    environment:
      - VIRTUAL_HOST=gunicorn-simle, pavement-hub.pavement.rutgers.edu, jupyter-minimal
      - GUNICORN_WORKERS=4
      - GUNICORN_ACCESSLOG=-
    #command: bash -c "gunicorn app.py -b 0.0.0.0:8000"
    expose:
      - "80"
    networks:
      - front-proxy
    depends_on:
      - nginx-proxy

  gunicorn-simple-app:
    image: gunicorn-simple
    container_name: gunicorn-simple-app
    environment:
      - GUNICORN_WORKERS=4
      - GUNICORN_ACCESSLOG=-
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=gunicorn.simple, gunicorn-simple
    depends_on:
      - nginx-proxy
    networks:
      - front-proxy
networks:
    front-proxy:
      driver: bridge
