version: '3.7'
services:
  nginx:
    build: ./nginx
    image: jhenck57/pavementhhub-nginx
    container_name: nginx
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/error.log:/etc/nginx/error_log.log
      #- ./nginx/cache/:/etc/nginx/cache
      #- /datastore/certifications/nginx/nginx-simple-docker/certs/:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENV=development
      - APPLICATION_URL=http://gunicorn-simple

    ports:
      - 80:80
      - 443:443
    #networks:
    #  - my-network

  gunicorn-simple:
    image: gunicorn-simple
    container_name: gunicorn-simple
    environment:
      - GUNICORN_WORKERS=4
      - GUNICORN_ACCESSLOG=-
    #command: bash -c "gunicorn app.py -b 0.0.0.0:8000"
    expose:
      - "80"
    #networks:
    #  - my-network

  gunicorn-simple2:
    image: gunicorn-simple
    container_name: gunicorn-simple2
    expose:
      - "80"
#networks:
#    my-network:
